DROP TABLE IF EXISTS X_INBOUNDMSG;

-- create tables
CREATE TABLE X_INBOUNDMSG(
  XINBOUND_ID VARCHAR(255) NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  STATE VARCHAR(10) NOT NULL,
  ORDERS_ID INT,
  ORDERSTATUS VARCHAR(10) NOT NULL,
  MSGCONTENT VARCHAR(2000),
  RETRYCOUNT INT,
  STORE_ID INT,
  TIMECREATED TIMESTAMP NULL DEFAULT NULL,
  TIMELOCKED TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(XINBOUND_ID)
);